import streamlit as st
import streamlit.components.v1 as components
import pandas as pd
import numpy as np
from PIL import Image

st.title('Ml4641 Team 5')
st.header("Midterm Report")
st.subheader("Intro/Background")
st.write("The National Basketball Association (NBA) is one of the biggest professional sports organizations in the world. With hundreds of players, dozens of teams, and over 1,000 games played per season, there is a vast amount of data available to analyze. Due to this, many efforts have been made to use AI and Machine Learning methods to predict basketball outcomes. IBM first utilized data mining in the 90’s with Advanced Scout, a tool for NBA management to better analyze hidden trends in basketball statistics (Colet, 1997). Independent projects have also been led, like Nigel Ma developing a model to predict a team’s playoff chances (Ma, 2021) or a group of Carnegie Mellon students using classification methods to predict individual game outcomes (Beckler, Wang, Papamichael).")
st.write("In this project, we are attempting to predict the winner of the NBA’s most prestigious recognition—the Most Valuable Player Award, meant to reward the greatest individual performance in competition contained to the given season. A linear regression model will be the foundation of the prediction for the MVP award, derived from a data set of over 15,000 player performances, 40 seasons, and 49 unique features. Using these unique features—including individual player statistics, team(s) played for, win shares, points, playing time, etc. over multiple years, we will train a model to predict the winners of different awards for the upcoming 2023-2024 NBA season.")
st.subheader("Problem Definition")
st.write("Our objective is to create a predictive model that can estimate the chances of an NBA player winning the MVP award. We aim to explore how player performance metrics relate to these award outcomes.")
st.subheader("Data Collection")
st.write("The dataset, sourced from Kaggle, specifically uses the 1982-2022 NBA Player Statistics with MVP Votes. To ensure data cleanliness and compatibility with scikit-learn, missing values in the dataset were filled with the mean of their respective columns, as scikit-learn does not work with null values. Additionally, a criterion was applied to filter out players whose minutes per game fell under one standard deviation from the mean. This step aims to exclude players who typically do not receive MVP votes due to playing time or performance levels considered below the norm.")
st.subheader("Methods")
st.write("Some columns of the dataset contained missing values, specifically statistics that involved some sort of percentage (i.e. 3 point percentage, free throw percentage, etc.). This was due to some players attempting zero shots, resulting in an undefined value. We decided that the best fix for this was to impute the mean of those columns, essentially making the assumption that if those players were to attempt shots, they would complete them at a percentage equal to the average of all other players in the league.")
st.write("To reduce the size of the dataset and remove irrelevant data (players that have essentially zero chance of winning the MVP award), we determined that for a player’s stats to be taken into account, they must meet a threshold of 10 minutes played per game, around one standard deviation from the mean. This removed around 3,000 rows, which will hopefully aid with model efficiency and accuracy. To further improve our models in the future, we will consider increasing this threshold to further narrow the dataset.")
st.write("To select the features for training, we made a few important modifications to the dataset. First, we removed some redundant features that could be derived from others; for example, since field goals made can be directly calculated from field goal percentage and field goals attempted, that column was removed.")
st.write("Next, we selected a group of features that we felt were crucial to a player’s MVP chances based on our previous knowledge of the sport. These are features like points, rebounds, assists, field goal percentage, etc.")
st.write("To further select important features, we utilized a basic variance threshold. All columns with a variance less than 1 were removed from the dataset. This was done as an effort to remove statistics that don’t vary much from player to player, and are therefore not informative when training our models. This removed around 15 features, leaving us with around 35. After examining the new list of features, we determined with our knowledge of the sport that they were a good representation of statistics that might impact a player’s MVP chances.")
st.write("When we have more models implemented in the future, we will explore utilizing other methods like forward or backward feature selection. This will be a more comprehensive method of determining the best features and will ensure maximum model accuracy.")
image = Image.open('variance.png')
st.image(image, caption='Variance of Features')
st.subheader("Results")
st.write("To evaluate and analyze our model using quantitative means we decided we could use Root Mean Squared Error(RMSE), Mean Absoluter Error (MAE), or R-squared. For the Midterm Report, we settled on RMSE.")
st.write("As discussed in our method, our data uses NBA statistics from 1982 - 2022. Our procedure was to perform Linear regression on the data from 1982-2021 and predict the last year so we can compare it to the last year of the dataset.")
st.write("Using this approach, we retrieved the 10 actual players with highest award share and compared the same players predicted award share.")
aimage = Image.open('act10.png')
st.image(aimage, caption='Actual Top 10 Award Share')
pimage = Image.open('pred10.png')
st.image(pimage, caption='Predicted Top 10 Award Share')
pimage = Image.open('sha10.png')
st.image(pimage, caption='Predicted Award Share of Actual Top 10')
st.write("The result of RMSE we received was 0.4705452156807155. Since this model is being used for a somewhat high-stakes prediction, and not a rough estimate, this is a higher score than what we would like to achieve.")
st.write("Additionally, the model predicted the majority of the same players, just differing rankings or award shares. This reiterates an accuracy problem, one we could possibly aim to fix through further training and usage of different prediction methods. Some methods we could possibly use could be random forest of gradient boosting methods.")
st.write("A major concern to solve, is that the current prediction doesn't account the fact that in real MVP voting, votes for one player mean less votes for the others. This why there are a lot of players with a higher predicted award share from the model than they may get in real life.")
st.subheader("Discussion")
st.write("Based on our results, there are also many external factors that play into MVP award share. The NBA MVP race is often swayed by other intangible factors that extend beyond points, rebounds, and assists. Media narratives play a pivotal role in shaping perceptions of a player's value to their team and the league as a whole. The storytelling surrounding a player's journey, clutch performances, and impact on the game's narrative can significantly influence MVP voting.")
st.write("Moreover, the phenomenon of voter fatigue in the NBA is another critical element to consider. As voters are human, there's a natural inclination to seek fresh narratives and recognize new standout performances. This tendency can impact the voting process, with players who have consistently performed at an elite level potentially facing challenges in securing MVP votes due to familiarity and the desire for novelty.")
st.subheader("3 Sources")
st.write("Bhandari, I., Colet, E., Parker, J. et al. Advanced Scout: Data Mining and Knowledge Discovery in NBA Data. Data Mining and Knowledge Discovery 1, 121–125 (1997). https://doi.org/10.1023/A:1009782106822")
st.write("N. Ma, NBA Playoff Prediction Using Several Machine Learning Methods, 2021 3rd International Conference on Machine Learning, Big Data and Business Intelligence (MLBDBI), Taiyuan, China, 2021, pp. 113-116, doi: 10.1109/MLBDBI54094.2021.00030.")
st.write("Beckler, M., Wang, H., &amp; Papamichael, M. (n.d.). (rep.). NBA Oracle. https://www.mbeckler.org/coursework/2008-2009/10701_report.pdf")
st.header("Contibution Table")
conSer = pd.Series(["Visualizations, Results, Predictions", "Predictions, Linear Regression, Methods", "Discussion, Data Cleaning, Data Collection", "Methods, Feature Selection, Data Cleaning", "Introduction, Problem Definition, Visualizations"], index=["Aditya", "Michael", "Sohum", "William", "David"])
conDf = pd.DataFrame(data=conSer, index=[
                     "Aditya", "Michael", "Sohum", "William", "David"],  columns=["Contributions"])
st.table(conDf)
